# Generated by Django 4.0.1 on 2025-11-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_on', '0001_initial'),
        ('rent', '0002_alter_payment_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='add_on.AddOn'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Reserved'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
