# Generated by Django 4.0.1 on 2025-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_bookingnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingdate',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
