# Generated by Django 5.2.7 on 2025-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='linked_booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='linked_review_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='linked_venue_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wishlistentry',
            name='linked_wishlist_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
