# Generated by Django 5.2.7 on 2025-12-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_linked_booking_id_comment_linked_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('Padel', 'Padel'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('Basket', 'Basket'), ('Sepak Bola', 'Sepak Bola'), ('Mini Soccer', 'Mini Soccer'), ('Futsal', 'Futsal'), ('Billiard', 'Billiard'), ('Tenis Meja', 'Tenis Meja'), ('Volly Ball', 'Volly Ball')], default='Tennis', max_length=20),
        ),
    ]
