# Generated by Django 4.0.1 on 2025-11-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_venue_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='comment',
            name='venue',
            field=models.ManyToManyField(related_name='comments', through='app.CommentVenue', to='app.Venue'),
        ),
    ]
