# Generated by Django 4.0.1 on 2025-11-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_venue_owner_venue_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
        migrations.CreateModel(
            name='WishlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_entries', to='app.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
