# Generated by Django 4.0.1 on 2025-11-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_addons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='venue',
            name='addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
