# Generated by Django 4.0.1 on 2025-11-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking_selected_addons_venue_addons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingNotification',
        ),
    ]
